[intervals]
api_key = "YOUR_API_KEY"
athlete_id = "0"
streak_carryover = 0

[display]
accent_color = "#FC4C02"
dark_mode = false
full_screen = false
width = 800
height = 480

[app]
refresh_time_minutes = 15

[sleep_mode]
enabled = false
start_hour = 22
end_hour = 8
